[package]
name = "legacylqs_rs"
version = "0.9.0"
authors = ["Francisco López <donflopez@gmail.com>"]
edition = "2018"

build = "build.rs"

[build-dependencies]
lalrpop = "0.17.0"

[dependencies]
lalrpop-util = "0.17.0"
regex = "1.1.6"
